import fetch from "node-fetch";

let urls = [
    "http://www.omdbapi.com/?apikey=af06aa57&s=star&page=1", 
    "http://www.omdbapi.com/?apikey=af06aa57&s=star&page=2", 
    "http://www.omdbapi.com/?apikey=af06aa57&s=star&page=3"
]

let genres = [
    { id: 28, name: 'Action' },
    { id: 12, name: 'Adventure' },
    { id: 16, name: 'Animation' },
    { id: 35, name: 'Comedy' },
    { id: 80, name: 'Crime' },
    { id: 99, name: 'Documentary' },
    { id: 18, name: 'Drama' },
    { id: 10751, name: 'Family' },
    { id: 14, name: 'Fantasy' },
    { id: 36, name: 'History' },
    { id: 27, name: 'Horror' },
    { id: 10402, name: 'Music' },
    { id: 9648, name: 'Mystery' },
    { id: 10749, name: 'Romance' },
    { id: 878, name: 'Science Fiction' },
    { id: 10770, name: 'TV Movie' },
    { id: 53, name: 'Thriller' },
    { id: 10752, name: 'War' },
    { id: 37, name: 'Western' }
]

let movies = [
    {
      adult: false,
      backdrop_path: '/A55WRPRK73zx1cuULDkdX4vriDO.jpg',
      genre_ids: [Array],
      id: 22599,
      original_language: 'en',
      original_title: 'Star',
      overview: "The Driver now carries an arrogant rock star who is visiting a major city (not Pittsburgh as earlier believed). Played by Madonna, this title character wants to get away from her bodyguards in the Driver's BMW. He soon gets tired of her and decides to have a bit of fun.",
      popularity: 5.688,
      poster_path: '/e9qcNtRSEgoYVrbns0pHInjuvyN.jpg',
      release_date: '2001-06-01',
      title: 'Star',
      video: false,
      vote_average: 6.638,
      vote_count: 112
    },
    {
      adult: false,
      backdrop_path: '/a1lMRUeGozBAczWaSoU1p3zLmGs.jpg',
      genre_ids: [Array],
      id: 136244,
      original_language: 'en',
      original_title: 'Star',
      overview: 'When Crystal Wyatt was 16 her father passed away. From that time her life would never be the same. Crystal is banished from the family ranch, and starts a new life as a singer in a San Francisco nightclub.',
      popularity: 2.272,
      poster_path: '/jYmt7JBvAmRJ0FxPx2UayOQ1uOB.jpg',
      release_date: '1993-09-20',
      title: 'Star',
      video: false,
      vote_average: 6.611,
      vote_count: 18
    },
    {
      adult: false,
      backdrop_path: '/m7hBkOBJomzIhbet60b6x4RTBRk.jpg',
      genre_ids: [Array],
      id: 52959,
      original_language: 'en',
      original_title: 'Star!',
      overview: 'Gertrude Lawrence rises to stage stardom at the cost of happiness.',
      popularity: 4.253,
      poster_path: '/xMyOm5hLWeuoWBea1DJrcJy8bU6.jpg',
      release_date: '1968-07-18',
      title: 'Star!',
      video: false,
      vote_average: 6.3,
      vote_count: 49
    },
    {
      adult: false,
      backdrop_path: '/iflKt34Ck2JpY2PY9wW1zwdJgJi.jpg',
      genre_ids: [Array],
      id: 782054,
      original_language: 'ja',
      original_title: '映画ドラえもん のび太の宇宙小戦争 2021',
      overview: 'One day during summer vacation, a palm-sized alien named Papi appears from a small rocket that Nobita picks up. He is the president of Pirika, a small planet in outer space, and has come to Earth to escape the rebels. Doraemon and his friends are puzzled by Papi’s small size, but as they play together using the secret tool “Small Light”, they gradually become friends. However, a whale-shaped space battleship comes to earth and attacks Doraemon, Nobita and the others in order to capture Papi. Feeling responsible for getting everyone involved, Papi tries to stand up to the rebels. Doraemon and his friends leave for the planet Pirika to protect their dear friend and his home.',
      popularity: 34.65,
      poster_path: '/48gKZioIDeUOI0afbYv3kh9u9RQ.jpg',
      release_date: '2022-03-04',
      title: "Doraemon: Nobita's Little Star Wars 2021",
      video: false,
      vote_average: 5.825,
      vote_count: 60
    },
    {
      adult: false,
      backdrop_path: '/2kvl6lcgoyAaf8cSRkzxE611u6T.jpg',
      genre_ids: [Array],
      id: 761898,
      original_language: 'ja',
      original_title: '劇場版 ソードアート・オンライン-プログレッシブ- 星なき夜のアリア',
      overview: "One month after Kayaba Akihiko's game of death began, the death toll continues to rise, two thousand players having already lost their lives to the ultra-difficult VRMMO world of Sword Art Online. On the day of the strategy meeting to plan out the first-floor boss battle, Kirito, a solo player who vows to fight alone to get stronger, runs into a rare, high-level female player. She gracefully dispatches powerful monsters with a single rapier that flashes like a shooting star in the night...",
      popularity: 47.316,
      poster_path: '/yD9RhgIVydQNBK7OLEbCWYcWMUd.jpg',
      release_date: '2021-10-30',
      title: 'Sword Art Online the Movie -Progressive- Aria of a Starless Night',
      video: false,
      vote_average: 8,
      vote_count: 197
    },
    {
      adult: false,
      backdrop_path: '/6XSDikVyntm4dHAacilTbWg8KvV.jpg',
      genre_ids: [Array],
      id: 939899,
      original_language: 'es',
      original_title: 'No mires a los ojos',
      overview: "Carpenter Sergio runs away and hides in a closet after his boss fired him. When the closet arrives at its buyer's house, he decides to stay there, hiding in his new home living with an unknown family.",
      popularity: 32.858,
      poster_path: '/8YHnuK9dowN47XAgSry4EtIuOBZ.jpg',
      release_date: '2022-11-04',
      title: 'Staring at Strangers',
      video: false,
      vote_average: 6.722,
      vote_count: 18
    },
    {
      adult: false,
      backdrop_path: '/osHpQQ5rcbmH41I4LQlPlprRGpk.jpg',
      genre_ids: [Array],
      id: 125225,
      original_language: 'hi',
      original_title: 'Star',
      overview: "Dev Kumar Verma comes from a middle-class family and must find employment to support his dad and mom. Dev, however, has set his mind upon becoming a music sensation like Elvis Presley. He loses his job because of this, and refuses to work until and unless he gets a job to his liking, much to the dismay of his parents and his brother, Shiv Kumar. Dev does get employment at Charlie's Disco, where he meets with Maya and falls in love with her.  When Charlie's Disco's competitor, Rana, finds out about Dev, he wants to hire Dev, but Dev decides to continue to work with Charlie's Disco, as a result Dev and Charlie get a beating by Rana's men, and Dev is unable to sing. After recuperating, Dev is devastated to find out that Maya and Shiv Kumar are in love with each other. What impact will this have on Dev and his brother on one hand, and what of his career in music?",
      popularity: 0.6,
      poster_path: '/pU7oXmVdNPrzj2XOGIQ6ciMnH42.jpg',
      release_date: '1982-10-22',
      title: 'Star',
      video: false,
      vote_average: 5.625,
      vote_count: 8
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 611791,
      original_language: 'fr',
      original_title: 'Star',
      overview: 'Star follows the path of Tito and Jay, two brothers living in the Montreal neighborhood of Park Extension. Accompanying these young people in their daily life marked by complicity and intimidation, Star tackles themes dear to teenagers: identity and friendship.',
      popularity: 0.936,
      poster_path: '/hVGnSMBc42TGwvV5QTHpH0PgyJp.jpg',
      release_date: '2015-09-30',
      title: 'Star',
      video: false,
      vote_average: 3.833,
      vote_count: 3
    },
    {
      adult: false,
      backdrop_path: '/zDImYTJiECn1b79segxKr382DSe.jpg',
      genre_ids: [Array],
      id: 449430,
      original_language: 'fr',
      original_title: 'Star',
      overview: 'Star is a young graffiti writer, the best in his city, Paris. His reputation attracts him as much into art galleries than in the police precincts. Accused of vandalism, he faces jail. Despite the threat, he decides to go to Rome with his crew in search of the meaning of his art.',
      popularity: 1.028,
      poster_path: '/zeGcw5pPVT4DhHrSLUDxE58QJQn.jpg',
      release_date: '2017-04-03',
      title: 'Star',
      video: false,
      vote_average: 7,
      vote_count: 5
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [Array],
      id: 719316,
      original_language: 'en',
      original_title: 'Star',
      overview: `Documentary short film and music video for MIKAL's song "Star", comprised of footage of the actual recording process of the song itself.`,     
      popularity: 0.6,
      poster_path: '/5o0GyNlILqVxfteo7l31wB5qD2X.jpg',
      release_date: '2017-01-23',
      title: 'Star',
      video: false,
      vote_average: 6.3,
      vote_count: 5
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [Array],
      id: 1050338,
      original_language: 'fr',
      original_title: 'Star',
      overview: 'Star follows the path of Tito and Jay, two brothers living in the Montreal neighborhood of Park Extension. Accompanying these young people in their daily life marked by complicity and intimidation, Star tackles themes dear to teenagers: identity and friendship.',
      popularity: 0.6,
      poster_path: null,
      release_date: '',
      title: 'Star',
      video: false,
      vote_average: 7,
      vote_count: 3
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [Array],
      id: 812434,
      original_language: 'it',
      original_title: 'Star',
      overview: 'Giacomo is a low-level actor and voice actor with a great passion for acting. After another disappointing audition he has one last chance to get the part assigned',
      popularity: 0.6,
      poster_path: '/4oObDGDhycViadrRCC2XJwwXAcR.jpg',
      release_date: '2019-12-19',
      title: 'Star',
      video: false,
      vote_average: 5.375,
      vote_count: 4
    },
    {
      adult: false,
      backdrop_path: '/6z9w8eidKWDDXwZNSVNaRolAYEP.jpg',
      genre_ids: [Array],
      id: 201,
      original_language: 'en',
      original_title: 'Star Trek: Nemesis',
      overview: 'En route to the honeymoon of William Riker to Deanna Troi on her home planet of Betazed, Captain Jean-Luc Picard and the crew of the U.S.S. Enterprise receives word from Starfleet that a coup has resulted in the installation of a new Romulan political leader, Shinzon, who claims to seek peace with the human-backed United Federation of Planets. Once in enemy territory, the captain and his crew make a startling discovery: Shinzon is human, a slave from the Romulan sister planet of Remus, and has a secret, shocking relationship to Picard himself.',
      popularity: 25.255,
      poster_path: '/cldAwhvBmOv9jrd3bXWuqRHoXyq.jpg',
      release_date: '2002-12-13',
      title: 'Star Trek: Nemesis',
      video: false,
      vote_average: 6.288,
      vote_count: 1227
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 1005573,
      original_language: 'en',
      original_title: 'S.T.A.R.',
      overview: "Following the Stonewall riots, Trans activists Marsha P. Johnson and Sylvia Rivera opened S.T.A.R. house, the first LGBTQ+ youth shelter in the world. Soon after, they're faced with the reality that their battle for equality has to be waged on two fronts.",
      popularity: 0.6,
      poster_path: null,
      release_date: '',
      title: 'S.T.A.R.',
      video: false,
      vote_average: 1,
      vote_count: 1
    },
    {
      adult: false,
      backdrop_path: '/9K1zhrS8jZ3NFZwzc5RgtwxskLT.jpg',
      genre_ids: [Array],
      id: 566451,
      original_language: 'ja',
      original_title: 'Re:ゼロから始める異世界生活 氷結の絆',
      overview: 'Covered in ice and snow, Elior Forest is the home to dangerous magical beasts and 50 elves frozen in ice. One day, the great spirit Puck helps a young girl break out of her ice prison. Her name is Emilia, a half-elf born with silver hair, long ears, and amethyst eyes—features that resemble the evil Witch who destroyed half the world long ago.  Shunned by society because of her appearance, Emilia dwells in the forest with Puck as her sole companion and family. Burdened with a sin of destruction she does not remember committing, she spends her days trying to find a way to help her frozen kin. But when the great spirit Melakuera, the Arbitrator of the world, finds Emilia, her right to stay alive is brought into question. Will the bonds of ice she formed with Puck prove to be the warm thread that defies fate?',
      popularity: 22.614,
      poster_path: '/ca2ZsUa4Qeik2IwlXFzV51hdxh0.jpg',
      release_date: '2019-11-08',
      title: 'Re:ZERO -Starting Life in Another World- The Frozen Bond',
      video: false,
      vote_average: 7.679,
      vote_count: 140
    },
    {
      adult: false,
      backdrop_path: '/aDYSnJAK0BTVeE8osOy22Kz3SXY.jpg',
      genre_ids: [Array],
      id: 11,
      original_language: 'en',
      original_title: 'Star Wars',
      overview: 'Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.',
      popularity: 84.281,
      poster_path: '/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg',
      release_date: '1977-05-25',
      title: 'Star Wars',
      video: false,
      vote_average: 8.207,
      vote_count: 18538
    },
    {
      adult: false,
      backdrop_path: '/t9ifVuOtSZBvtieF9L83pnHnOcC.jpg',
      genre_ids: [Array],
      id: 532321,
      original_language: 'ja',
      original_title: 'Re:ゼロから始める異世界生活 Memory Snow',
      overview: `Subaru and friends finally get a moment of peace, and Subaru goes on a certain secret mission that he must not let anyone find out about! However, even though Subaru is wearing a disguise, Petra and other children of the village immediately figure out who he is. Now that his mission was exposed within five seconds of it starting, what will happen with Subaru's "date course" with Emilia?`,
      popularity: 14.281,
      poster_path: '/y7XwmyE5ue9hjk65fEWpO2hGU2B.jpg',
      release_date: '2018-10-06',
      title: 'Re:ZERO -Starting Life in Another World- Memory Snow',
      video: false,
      vote_average: 7.399,
      vote_count: 238
    },
    {
      adult: false,
      backdrop_path: '/zojlWX59bx5lgJCfJxMtKIVgNSI.jpg',
      genre_ids: [Array],
      id: 779019,
      original_language: 'ja',
      original_title: 'グリザイア：ファントムトリガー THE ANIMATION スターゲイザー',
      overview: "While Rena and Maki recover from their injuries, the other SORD members jet off overseas for a school trip. Within moments of their arrival, though, the Mihama gang are pulled into a manhunt for a SORD deserter, assisted by student Sylvia and Velvet of St. Aile's International School. Tohka's the star of the show this time round, but she's wrestling with her own issues - old memories of her parents, and a promise to a friend that she wasn't able to keep...", 
      popularity: 62.215,
      poster_path: '/zNaweWLkwIAsrdeBq4Hu6j6EO5a.jpg',
      release_date: '2020-11-27',
      title: 'Grisaia: Phantom Trigger The Animation - Stargazer',
      video: false,
      vote_average: 8,
      vote_count: 4
    },
    {
      adult: false,
      backdrop_path: '/tXPDZQZqoxYNTNohXVgFSHNWoio.jpg',
      genre_ids: [Array],
      overview: `Two Hong-Kong cops are sent to Tokyo to catch an ex-cop who stole a large amount of money in diamonds. After one is captured by the Ninja-gang protecting the rogue cop, the other one gets his old Orphanage gang, dubbed the "Five Lucky Stars," to help him. They don't like this much, but they do it.`,   
      popularity: 15.786,
      poster_path: '/dZzHBIcJsld2XMvwR75OZGf4NM2.jpg',      release_date: '1985-02-10',      title: 'My Lucky Stars',
      video: false,
      vote_average: 6.359,
      vote_count: 128
    }
  ]

const fetchData = async (url) => {
    let res = await fetch(url)
    let data = await res.json()
    return data
}

//let results = await Promise.all([urls.map(url => fetchData(url))])
    
//console.log(await Promise.all([urls.map(url => fetchData(url))]))
    
fetch("https://api.themoviedb.org/3/movie/1894/similar?api_key=749143172af59e585141e6c1c0adc7a0&region=UK")
    .then(res => res.json())
    .then(res => console.log(res))
